import { invoke } from '@tauri-apps/api/core'

export const desktop = {
  listProjects: () => invoke('list_projects'),
  addProject: (path) => invoke('add_project', { path }),
  touchProject: (id) => invoke('touch_project', { id }),
  removeProject: (id) => invoke('remove_project', { id }),
  listConversations: (projectId) => invoke('list_conversations', { projectId }),
  createConversation: (projectId) => invoke('create_conversation', { projectId }),
  renameConversation: (id, title) => invoke('rename_conversation', { id, title }),
  touchConversation: (id) => invoke('touch_conversation', { id }),
  deleteConversation: (id) => invoke('delete_conversation', { id }),
  listMessages: (conversationId) => invoke('list_messages', { conversationId }),
  saveMessage: (conversationId, role, content) => invoke('save_message', { conversationId, role, content }),
  listAttachments: (conversationId) => invoke('list_attachments', { conversationId }),
  linkAttachments: (messageId, attachmentIds) => invoke('link_attachments', { messageId, attachmentIds }),
  loadSettings: () => invoke('load_settings'),
  saveSettings: (settings) => invoke('save_settings', { settings }),
  loadClaudeSettings: () => invoke('load_claude_settings'),
  saveClaudeSettings: (content) => invoke('save_claude_settings', { content }),
  copyAttachment: (conversationId, sourcePath) => invoke('copy_attachment', { conversationId, sourcePath }),
  saveClipboardImage: (conversationId, bytes, extension) => invoke('save_clipboard_image', { conversationId, bytes, extension }),
  resolveLocalFiles: (projectPath, candidates) => invoke('resolve_local_files', { projectPath, candidates }),
  downloadFile: (projectPath, sourcePath, destinationPath) => invoke('download_file', { projectPath, sourcePath, destinationPath }),
  readProjectFile: (projectPath, sourcePath) => invoke('read_project_file', { projectPath, sourcePath }),
  openInEditor: (path, line, editor) => invoke('open_in_editor', { path, line, editor }),
  revealPath: (path) => invoke('reveal_path', { path }),
  openTerminal: (path) => invoke('open_terminal', { path }),
  gitStatus: (projectPath) => invoke('git_status', { projectPath }),
  gitDiff: (projectPath, path) => invoke('git_diff', { projectPath, path }),
  checkClaude: (command, env) => invoke('check_claude', { command, env }),
  sendClaude: (request) => invoke('send_claude', { request }),
  interruptClaude: (conversationId) => invoke('interrupt_claude', { conversationId }),
  stopClaude: (conversationId) => invoke('stop_claude', { conversationId }),
}
